services:
  edsger-dev:
    build:
      context: ./Edsger_v0
      dockerfile: Dockerfile
    image: postulate-edsger
    container_name: postulate-edsger-dev
    stdin_open: true  # -i opció (interaktív bemenet)
    tty: true         # -t opció (pszeudo-TTY a terminálhoz)
    entrypoint: ["/bin/bash"]
    volumes:
      - ./Edsger_v0:/workspace/Edsger
