/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 87
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 68
#define ALIAS_COUNT 0
#define TOKEN_COUNT 46
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_comment_token1 = 1,
  aux_sym_comment_token2 = 2,
  anon_sym_int8 = 3,
  anon_sym_int16 = 4,
  anon_sym_int = 5,
  anon_sym_int32 = 6,
  anon_sym_int64 = 7,
  anon_sym_uint8 = 8,
  anon_sym_uint16 = 9,
  anon_sym_uint = 10,
  anon_sym_uint32 = 11,
  anon_sym_uint64 = 12,
  anon_sym_bool = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  anon_sym_mut = 16,
  anon_sym_const = 17,
  anon_sym_COLON = 18,
  anon_sym_COLON_EQ = 19,
  anon_sym_SEMI = 20,
  anon_sym_COMMA = 21,
  anon_sym_function = 22,
  anon_sym_LPAREN = 23,
  anon_sym_RPAREN = 24,
  anon_sym_LBRACE = 25,
  anon_sym_RBRACE = 26,
  anon_sym_return = 27,
  anon_sym_if = 28,
  anon_sym_else = 29,
  anon_sym_while = 30,
  anon_sym_PLUS = 31,
  anon_sym_DASH = 32,
  anon_sym_STAR = 33,
  anon_sym_SLASH = 34,
  anon_sym_EQ_EQ = 35,
  anon_sym_BANG_EQ = 36,
  anon_sym_LT = 37,
  anon_sym_GT = 38,
  anon_sym_LT_EQ = 39,
  anon_sym_GT_EQ = 40,
  sym_identifier = 41,
  aux_sym_number_literal_token1 = 42,
  aux_sym_number_literal_token2 = 43,
  anon_sym_true = 44,
  anon_sym_false = 45,
  sym_source_file = 46,
  sym__statement = 47,
  sym_comment = 48,
  sym_type = 49,
  sym_array_type = 50,
  sym_variable_declaration = 51,
  sym_assignment = 52,
  sym_function_declaration = 53,
  sym_parameter_list = 54,
  sym_parameter = 55,
  sym_block = 56,
  sym_return_statement = 57,
  sym_if_statement = 58,
  sym_while_statement = 59,
  sym__expression = 60,
  sym_binary_expression = 61,
  sym_number_literal = 62,
  sym_boolean_literal = 63,
  aux_sym_source_file_repeat1 = 64,
  aux_sym_assignment_repeat1 = 65,
  aux_sym_assignment_repeat2 = 66,
  aux_sym_parameter_list_repeat1 = 67,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_int8] = "int8",
  [anon_sym_int16] = "int16",
  [anon_sym_int] = "int",
  [anon_sym_int32] = "int32",
  [anon_sym_int64] = "int64",
  [anon_sym_uint8] = "uint8",
  [anon_sym_uint16] = "uint16",
  [anon_sym_uint] = "uint",
  [anon_sym_uint32] = "uint32",
  [anon_sym_uint64] = "uint64",
  [anon_sym_bool] = "bool",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_mut] = "mut",
  [anon_sym_const] = "const",
  [anon_sym_COLON] = ":",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [anon_sym_function] = "function",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_return] = "return",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [sym_identifier] = "identifier",
  [aux_sym_number_literal_token1] = "number_literal_token1",
  [aux_sym_number_literal_token2] = "number_literal_token2",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_comment] = "comment",
  [sym_type] = "type",
  [sym_array_type] = "array_type",
  [sym_variable_declaration] = "variable_declaration",
  [sym_assignment] = "assignment",
  [sym_function_declaration] = "function_declaration",
  [sym_parameter_list] = "parameter_list",
  [sym_parameter] = "parameter",
  [sym_block] = "block",
  [sym_return_statement] = "return_statement",
  [sym_if_statement] = "if_statement",
  [sym_while_statement] = "while_statement",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_number_literal] = "number_literal",
  [sym_boolean_literal] = "boolean_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_assignment_repeat1] = "assignment_repeat1",
  [aux_sym_assignment_repeat2] = "assignment_repeat2",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_int8] = anon_sym_int8,
  [anon_sym_int16] = anon_sym_int16,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_int32] = anon_sym_int32,
  [anon_sym_int64] = anon_sym_int64,
  [anon_sym_uint8] = anon_sym_uint8,
  [anon_sym_uint16] = anon_sym_uint16,
  [anon_sym_uint] = anon_sym_uint,
  [anon_sym_uint32] = anon_sym_uint32,
  [anon_sym_uint64] = anon_sym_uint64,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_mut] = anon_sym_mut,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [sym_identifier] = sym_identifier,
  [aux_sym_number_literal_token1] = aux_sym_number_literal_token1,
  [aux_sym_number_literal_token2] = aux_sym_number_literal_token2,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_comment] = sym_comment,
  [sym_type] = sym_type,
  [sym_array_type] = sym_array_type,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_assignment] = sym_assignment,
  [sym_function_declaration] = sym_function_declaration,
  [sym_parameter_list] = sym_parameter_list,
  [sym_parameter] = sym_parameter,
  [sym_block] = sym_block,
  [sym_return_statement] = sym_return_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_while_statement] = sym_while_statement,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_number_literal] = sym_number_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_assignment_repeat1] = aux_sym_assignment_repeat1,
  [aux_sym_assignment_repeat2] = aux_sym_assignment_repeat2,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_int8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uint8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uint16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uint32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uint64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mut] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_number_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_while_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_assignment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_assignment_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alternative = 1,
  field_body = 2,
  field_condition = 3,
  field_consequence = 4,
  field_name = 5,
  field_return_type = 6,
  field_type = 7,
  field_value = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_name] = "name",
  [field_return_type] = "return_type",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 3},
  [6] = {.index = 11, .length = 2},
  [7] = {.index = 13, .length = 3},
  [8] = {.index = 16, .length = 3},
  [9] = {.index = 19, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_condition, 1},
    {field_consequence, 2},
  [2] =
    {field_body, 2},
    {field_condition, 1},
  [4] =
    {field_name, 1},
    {field_type, 3},
  [6] =
    {field_body, 4},
    {field_name, 1},
  [8] =
    {field_alternative, 4},
    {field_condition, 1},
    {field_consequence, 2},
  [11] =
    {field_body, 5},
    {field_name, 1},
  [13] =
    {field_name, 1},
    {field_type, 3},
    {field_value, 5},
  [16] =
    {field_body, 6},
    {field_name, 1},
    {field_return_type, 5},
  [19] =
    {field_body, 7},
    {field_name, 1},
    {field_return_type, 6},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 32,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 31,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(27);
      ADVANCE_MAP(
        '!', 13,
        '(', 62,
        ')', 63,
        '*', 73,
        '+', 71,
        ',', 60,
        '-', 72,
        '/', 74,
        ':', 57,
        ';', 59,
        '<', 77,
        '=', 15,
        '>', 78,
        '[', 52,
        ']', 53,
        'b', 112,
        'c', 110,
        'e', 101,
        'f', 87,
        'i', 95,
        'm', 127,
        'r', 94,
        't', 114,
        'u', 99,
        'w', 97,
        '{', 64,
        '}', 65,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(62);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ';') ADVANCE(59);
      if (lookahead == 'f') ADVANCE(88);
      if (lookahead == 't') ADVANCE(114);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(63);
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(28);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == 'b') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(16);
      if (lookahead == 'u') ADVANCE(17);
      if (lookahead == '{') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      END_STATE();
    case 7:
      if (lookahead == '2') ADVANCE(36);
      END_STATE();
    case 8:
      if (lookahead == '2') ADVANCE(46);
      END_STATE();
    case 9:
      if (lookahead == '4') ADVANCE(38);
      END_STATE();
    case 10:
      if (lookahead == '4') ADVANCE(48);
      END_STATE();
    case 11:
      if (lookahead == '6') ADVANCE(32);
      END_STATE();
    case 12:
      if (lookahead == '6') ADVANCE(42);
      END_STATE();
    case 13:
      if (lookahead == '=') ADVANCE(76);
      END_STATE();
    case 14:
      if (lookahead == '=') ADVANCE(58);
      END_STATE();
    case 15:
      if (lookahead == '=') ADVANCE(75);
      END_STATE();
    case 16:
      if (lookahead == 'f') ADVANCE(67);
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(50);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(130);
      END_STATE();
    case 25:
      if (eof) ADVANCE(27);
      ADVANCE_MAP(
        ')', 63,
        ',', 60,
        '/', 3,
        ':', 14,
        ';', 59,
        '[', 52,
        'c', 110,
        'f', 126,
        'i', 96,
        'm', 127,
        'r', 94,
        'w', 97,
        '{', 64,
        '}', 65,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 26:
      if (eof) ADVANCE(27);
      ADVANCE_MAP(
        '/', 3,
        'c', 110,
        'e', 101,
        'f', 126,
        'i', 96,
        'm', 127,
        'r', 94,
        'w', 97,
        '}', 65,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_int8);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_int8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_int16);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_int16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_int);
      if (lookahead == '1') ADVANCE(85);
      if (lookahead == '3') ADVANCE(81);
      if (lookahead == '6') ADVANCE(83);
      if (lookahead == '8') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_int);
      if (lookahead == '1') ADVANCE(11);
      if (lookahead == '3') ADVANCE(7);
      if (lookahead == '6') ADVANCE(9);
      if (lookahead == '8') ADVANCE(30);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_int32);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_int32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_int64);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_int64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_uint8);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_uint8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_uint16);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_uint16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_uint);
      if (lookahead == '1') ADVANCE(86);
      if (lookahead == '3') ADVANCE(82);
      if (lookahead == '6') ADVANCE(84);
      if (lookahead == '8') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_uint);
      if (lookahead == '1') ADVANCE(12);
      if (lookahead == '3') ADVANCE(8);
      if (lookahead == '6') ADVANCE(10);
      if (lookahead == '8') ADVANCE(40);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_uint32);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_uint32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_uint64);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_uint64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_bool);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_mut);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_const);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_function);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_while);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(28);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(79);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(80);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '6') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '6') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(104);
      if (lookahead == 'u') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(124);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(133);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(123);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(68);
      if (lookahead == 'n') ADVANCE(119);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(109);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(113);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(116);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(118);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(121);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(111);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(107);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(128);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(125);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(120);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(aux_sym_number_literal_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(130);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(aux_sym_number_literal_token2);
      if (lookahead == 'n') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 25},
  [2] = {.lex_state = 25},
  [3] = {.lex_state = 25},
  [4] = {.lex_state = 25},
  [5] = {.lex_state = 25},
  [6] = {.lex_state = 25},
  [7] = {.lex_state = 25},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 26},
  [31] = {.lex_state = 26},
  [32] = {.lex_state = 26},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 25},
  [38] = {.lex_state = 25},
  [39] = {.lex_state = 25},
  [40] = {.lex_state = 25},
  [41] = {.lex_state = 25},
  [42] = {.lex_state = 25},
  [43] = {.lex_state = 25},
  [44] = {.lex_state = 25},
  [45] = {.lex_state = 25},
  [46] = {.lex_state = 25},
  [47] = {.lex_state = 25},
  [48] = {.lex_state = 25},
  [49] = {.lex_state = 25},
  [50] = {.lex_state = 25},
  [51] = {.lex_state = 25},
  [52] = {.lex_state = 25},
  [53] = {.lex_state = 25},
  [54] = {.lex_state = 25},
  [55] = {.lex_state = 25},
  [56] = {.lex_state = 6},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 25},
  [63] = {.lex_state = 25},
  [64] = {.lex_state = 25},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 25},
  [68] = {.lex_state = 6},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 25},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 2},
  [78] = {.lex_state = 2},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 6},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 6},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 2},
  [86] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(3),
    [aux_sym_comment_token2] = ACTIONS(3),
    [anon_sym_int8] = ACTIONS(1),
    [anon_sym_int16] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_int32] = ACTIONS(1),
    [anon_sym_int64] = ACTIONS(1),
    [anon_sym_uint8] = ACTIONS(1),
    [anon_sym_uint16] = ACTIONS(1),
    [anon_sym_uint] = ACTIONS(1),
    [anon_sym_uint32] = ACTIONS(1),
    [anon_sym_uint64] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_mut] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym_number_literal_token1] = ACTIONS(1),
    [aux_sym_number_literal_token2] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(80),
    [sym__statement] = STATE(47),
    [sym_comment] = STATE(1),
    [sym_variable_declaration] = STATE(53),
    [sym_assignment] = STATE(53),
    [sym_function_declaration] = STATE(53),
    [sym_return_statement] = STATE(53),
    [sym_if_statement] = STATE(53),
    [sym_while_statement] = STATE(53),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_comment_token1] = ACTIONS(3),
    [aux_sym_comment_token2] = ACTIONS(3),
    [anon_sym_mut] = ACTIONS(7),
    [anon_sym_const] = ACTIONS(7),
    [anon_sym_function] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_while] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(24), 1,
      anon_sym_function,
    ACTIONS(27), 1,
      anon_sym_return,
    ACTIONS(30), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_while,
    ACTIONS(36), 1,
      sym_identifier,
    STATE(47), 1,
      sym__statement,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(21), 2,
      anon_sym_mut,
      anon_sym_const,
    STATE(2), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(53), 6,
      sym_variable_declaration,
      sym_assignment,
      sym_function_declaration,
      sym_return_statement,
      sym_if_statement,
      sym_while_statement,
  [43] = 12,
    ACTIONS(9), 1,
      anon_sym_function,
    ACTIONS(11), 1,
      anon_sym_return,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    STATE(3), 1,
      sym_comment,
    STATE(5), 1,
      aux_sym_source_file_repeat1,
    STATE(47), 1,
      sym__statement,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(7), 2,
      anon_sym_mut,
      anon_sym_const,
    STATE(53), 6,
      sym_variable_declaration,
      sym_assignment,
      sym_function_declaration,
      sym_return_statement,
      sym_if_statement,
      sym_while_statement,
  [87] = 12,
    ACTIONS(9), 1,
      anon_sym_function,
    ACTIONS(11), 1,
      anon_sym_return,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(4), 1,
      sym_comment,
    STATE(47), 1,
      sym__statement,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(7), 2,
      anon_sym_mut,
      anon_sym_const,
    STATE(53), 6,
      sym_variable_declaration,
      sym_assignment,
      sym_function_declaration,
      sym_return_statement,
      sym_if_statement,
      sym_while_statement,
  [131] = 12,
    ACTIONS(9), 1,
      anon_sym_function,
    ACTIONS(11), 1,
      anon_sym_return,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(5), 1,
      sym_comment,
    STATE(47), 1,
      sym__statement,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(7), 2,
      anon_sym_mut,
      anon_sym_const,
    STATE(53), 6,
      sym_variable_declaration,
      sym_assignment,
      sym_function_declaration,
      sym_return_statement,
      sym_if_statement,
      sym_while_statement,
  [175] = 12,
    ACTIONS(9), 1,
      anon_sym_function,
    ACTIONS(11), 1,
      anon_sym_return,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      aux_sym_source_file_repeat1,
    STATE(6), 1,
      sym_comment,
    STATE(47), 1,
      sym__statement,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(7), 2,
      anon_sym_mut,
      anon_sym_const,
    STATE(53), 6,
      sym_variable_declaration,
      sym_assignment,
      sym_function_declaration,
      sym_return_statement,
      sym_if_statement,
      sym_while_statement,
  [219] = 12,
    ACTIONS(9), 1,
      anon_sym_function,
    ACTIONS(11), 1,
      anon_sym_return,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(7), 1,
      sym_comment,
    STATE(47), 1,
      sym__statement,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(7), 2,
      anon_sym_mut,
      anon_sym_const,
    STATE(53), 6,
      sym_variable_declaration,
      sym_assignment,
      sym_function_declaration,
      sym_return_statement,
      sym_if_statement,
      sym_while_statement,
  [263] = 4,
    STATE(8), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(51), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [290] = 4,
    STATE(9), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(55), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 11,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [316] = 4,
    STATE(10), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(59), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(57), 11,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [342] = 4,
    STATE(11), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(63), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(61), 11,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [368] = 4,
    STATE(12), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(67), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(65), 11,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [394] = 6,
    STATE(13), 1,
      sym_comment,
    STATE(54), 1,
      sym_array_type,
    STATE(59), 1,
      sym_type,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(71), 2,
      anon_sym_int,
      anon_sym_uint,
    ACTIONS(69), 9,
      anon_sym_int8,
      anon_sym_int16,
      anon_sym_int32,
      anon_sym_int64,
      anon_sym_uint8,
      anon_sym_uint16,
      anon_sym_uint32,
      anon_sym_uint64,
      anon_sym_bool,
  [423] = 7,
    ACTIONS(73), 1,
      anon_sym_SEMI,
    ACTIONS(75), 1,
      anon_sym_COMMA,
    STATE(14), 1,
      sym_comment,
    STATE(72), 1,
      aux_sym_assignment_repeat2,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(79), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [454] = 6,
    STATE(15), 1,
      sym_comment,
    STATE(54), 1,
      sym_array_type,
    STATE(66), 1,
      sym_type,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(71), 2,
      anon_sym_int,
      anon_sym_uint,
    ACTIONS(69), 9,
      anon_sym_int8,
      anon_sym_int16,
      anon_sym_int32,
      anon_sym_int64,
      anon_sym_uint8,
      anon_sym_uint16,
      anon_sym_uint32,
      anon_sym_uint64,
      anon_sym_bool,
  [483] = 7,
    ACTIONS(75), 1,
      anon_sym_COMMA,
    ACTIONS(81), 1,
      anon_sym_SEMI,
    STATE(16), 1,
      sym_comment,
    STATE(61), 1,
      aux_sym_assignment_repeat2,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(79), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [514] = 6,
    STATE(17), 1,
      sym_comment,
    STATE(54), 1,
      sym_array_type,
    STATE(70), 1,
      sym_type,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(71), 2,
      anon_sym_int,
      anon_sym_uint,
    ACTIONS(69), 9,
      anon_sym_int8,
      anon_sym_int16,
      anon_sym_int32,
      anon_sym_int64,
      anon_sym_uint8,
      anon_sym_uint16,
      anon_sym_uint32,
      anon_sym_uint64,
      anon_sym_bool,
  [543] = 6,
    STATE(18), 1,
      sym_comment,
    STATE(54), 1,
      sym_array_type,
    STATE(67), 1,
      sym_type,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(71), 2,
      anon_sym_int,
      anon_sym_uint,
    ACTIONS(69), 9,
      anon_sym_int8,
      anon_sym_int16,
      anon_sym_int32,
      anon_sym_int64,
      anon_sym_uint8,
      anon_sym_uint16,
      anon_sym_uint32,
      anon_sym_uint64,
      anon_sym_bool,
  [572] = 6,
    ACTIONS(83), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym_comment,
    STATE(30), 1,
      sym_block,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(79), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [600] = 6,
    ACTIONS(85), 1,
      anon_sym_LBRACE,
    STATE(20), 1,
      sym_comment,
    STATE(45), 1,
      sym_block,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(79), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [628] = 5,
    STATE(21), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(87), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(79), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [654] = 5,
    ACTIONS(89), 1,
      anon_sym_RPAREN,
    STATE(22), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(79), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [679] = 10,
    ACTIONS(91), 1,
      anon_sym_SEMI,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      aux_sym_number_literal_token1,
    ACTIONS(99), 1,
      aux_sym_number_literal_token2,
    STATE(23), 1,
      sym_comment,
    STATE(24), 1,
      sym__expression,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(101), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 3,
      sym_binary_expression,
      sym_number_literal,
      sym_boolean_literal,
  [714] = 5,
    ACTIONS(103), 1,
      anon_sym_SEMI,
    STATE(24), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(79), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [739] = 5,
    ACTIONS(105), 1,
      anon_sym_SEMI,
    STATE(25), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(79), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [764] = 9,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      aux_sym_number_literal_token1,
    ACTIONS(99), 1,
      aux_sym_number_literal_token2,
    STATE(19), 1,
      sym__expression,
    STATE(26), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(101), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 3,
      sym_binary_expression,
      sym_number_literal,
      sym_boolean_literal,
  [796] = 9,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      aux_sym_number_literal_token1,
    ACTIONS(99), 1,
      aux_sym_number_literal_token2,
    STATE(10), 1,
      sym__expression,
    STATE(27), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(101), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 3,
      sym_binary_expression,
      sym_number_literal,
      sym_boolean_literal,
  [828] = 9,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      aux_sym_number_literal_token1,
    ACTIONS(99), 1,
      aux_sym_number_literal_token2,
    STATE(16), 1,
      sym__expression,
    STATE(28), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(101), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 3,
      sym_binary_expression,
      sym_number_literal,
      sym_boolean_literal,
  [860] = 9,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      aux_sym_number_literal_token1,
    ACTIONS(99), 1,
      aux_sym_number_literal_token2,
    STATE(22), 1,
      sym__expression,
    STATE(29), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(101), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 3,
      sym_binary_expression,
      sym_number_literal,
      sym_boolean_literal,
  [892] = 5,
    ACTIONS(111), 1,
      anon_sym_else,
    STATE(30), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(109), 7,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [916] = 4,
    STATE(31), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(113), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(115), 8,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      sym_identifier,
  [938] = 4,
    STATE(32), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(117), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(119), 8,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      sym_identifier,
  [960] = 9,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      aux_sym_number_literal_token1,
    ACTIONS(99), 1,
      aux_sym_number_literal_token2,
    STATE(25), 1,
      sym__expression,
    STATE(33), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(101), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 3,
      sym_binary_expression,
      sym_number_literal,
      sym_boolean_literal,
  [992] = 9,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      aux_sym_number_literal_token1,
    ACTIONS(99), 1,
      aux_sym_number_literal_token2,
    STATE(21), 1,
      sym__expression,
    STATE(34), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(101), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 3,
      sym_binary_expression,
      sym_number_literal,
      sym_boolean_literal,
  [1024] = 9,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      aux_sym_number_literal_token1,
    ACTIONS(99), 1,
      aux_sym_number_literal_token2,
    STATE(14), 1,
      sym__expression,
    STATE(35), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(101), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 3,
      sym_binary_expression,
      sym_number_literal,
      sym_boolean_literal,
  [1056] = 9,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      aux_sym_number_literal_token1,
    ACTIONS(99), 1,
      aux_sym_number_literal_token2,
    STATE(20), 1,
      sym__expression,
    STATE(36), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(101), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 3,
      sym_binary_expression,
      sym_number_literal,
      sym_boolean_literal,
  [1088] = 4,
    STATE(37), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(121), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(123), 7,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1109] = 4,
    STATE(38), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(125), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(127), 7,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1130] = 4,
    STATE(39), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(129), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(131), 7,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1151] = 4,
    STATE(40), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(133), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(135), 7,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1172] = 4,
    STATE(41), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(137), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(139), 7,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1193] = 4,
    STATE(42), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(141), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(143), 7,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1214] = 4,
    STATE(43), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(145), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(147), 7,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1235] = 4,
    STATE(44), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(149), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(151), 7,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1256] = 4,
    STATE(45), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(153), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(155), 7,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1277] = 4,
    STATE(46), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(157), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(159), 7,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1298] = 4,
    STATE(47), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(161), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(163), 7,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1319] = 4,
    STATE(48), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(117), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(119), 7,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1340] = 4,
    STATE(49), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(165), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(167), 7,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1361] = 4,
    STATE(50), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(169), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(171), 7,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1382] = 4,
    STATE(51), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(175), 7,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1403] = 4,
    STATE(52), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(113), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(115), 7,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1424] = 4,
    STATE(53), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(177), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(179), 7,
      anon_sym_mut,
      anon_sym_const,
      anon_sym_function,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1445] = 3,
    STATE(54), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(181), 6,
      anon_sym_LBRACK,
      anon_sym_COLON_EQ,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [1461] = 3,
    STATE(55), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(183), 6,
      anon_sym_LBRACK,
      anon_sym_COLON_EQ,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [1477] = 5,
    ACTIONS(85), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_if,
    STATE(56), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    STATE(42), 2,
      sym_block,
      sym_if_statement,
  [1495] = 6,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    ACTIONS(189), 1,
      sym_identifier,
    STATE(57), 1,
      sym_comment,
    STATE(73), 1,
      sym_parameter,
    STATE(82), 1,
      sym_parameter_list,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1515] = 5,
    ACTIONS(191), 1,
      anon_sym_COMMA,
    ACTIONS(193), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      sym_comment,
    STATE(69), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1532] = 5,
    ACTIONS(85), 1,
      anon_sym_LBRACE,
    ACTIONS(195), 1,
      anon_sym_LBRACK,
    STATE(50), 1,
      sym_block,
    STATE(59), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1549] = 5,
    ACTIONS(85), 1,
      anon_sym_LBRACE,
    ACTIONS(197), 1,
      anon_sym_COLON,
    STATE(46), 1,
      sym_block,
    STATE(60), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1566] = 5,
    ACTIONS(75), 1,
      anon_sym_COMMA,
    ACTIONS(199), 1,
      anon_sym_SEMI,
    STATE(61), 1,
      sym_comment,
    STATE(65), 1,
      aux_sym_assignment_repeat2,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1583] = 4,
    ACTIONS(201), 1,
      anon_sym_COLON_EQ,
    ACTIONS(203), 1,
      anon_sym_COMMA,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    STATE(62), 2,
      sym_comment,
      aux_sym_assignment_repeat1,
  [1598] = 5,
    ACTIONS(206), 1,
      anon_sym_COLON_EQ,
    ACTIONS(208), 1,
      anon_sym_COMMA,
    STATE(63), 1,
      sym_comment,
    STATE(64), 1,
      aux_sym_assignment_repeat1,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1615] = 5,
    ACTIONS(208), 1,
      anon_sym_COMMA,
    ACTIONS(210), 1,
      anon_sym_COLON_EQ,
    STATE(62), 1,
      aux_sym_assignment_repeat1,
    STATE(64), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1632] = 4,
    ACTIONS(87), 1,
      anon_sym_SEMI,
    ACTIONS(212), 1,
      anon_sym_COMMA,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    STATE(65), 2,
      sym_comment,
      aux_sym_assignment_repeat2,
  [1647] = 4,
    ACTIONS(195), 1,
      anon_sym_LBRACK,
    STATE(66), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(215), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1662] = 5,
    ACTIONS(195), 1,
      anon_sym_LBRACK,
    ACTIONS(217), 1,
      anon_sym_COLON_EQ,
    ACTIONS(219), 1,
      anon_sym_SEMI,
    STATE(67), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1679] = 5,
    ACTIONS(85), 1,
      anon_sym_LBRACE,
    ACTIONS(221), 1,
      anon_sym_COLON,
    STATE(41), 1,
      sym_block,
    STATE(68), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1696] = 4,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(226), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    STATE(69), 2,
      sym_comment,
      aux_sym_parameter_list_repeat1,
  [1711] = 5,
    ACTIONS(85), 1,
      anon_sym_LBRACE,
    ACTIONS(195), 1,
      anon_sym_LBRACK,
    STATE(51), 1,
      sym_block,
    STATE(70), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1728] = 5,
    ACTIONS(97), 1,
      aux_sym_number_literal_token1,
    ACTIONS(99), 1,
      aux_sym_number_literal_token2,
    STATE(71), 1,
      sym_comment,
    STATE(79), 1,
      sym_number_literal,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1745] = 5,
    ACTIONS(75), 1,
      anon_sym_COMMA,
    ACTIONS(81), 1,
      anon_sym_SEMI,
    STATE(65), 1,
      aux_sym_assignment_repeat2,
    STATE(72), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1762] = 5,
    ACTIONS(191), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_parameter_list_repeat1,
    STATE(73), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1779] = 4,
    ACTIONS(189), 1,
      sym_identifier,
    STATE(74), 1,
      sym_comment,
    STATE(76), 1,
      sym_parameter,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1793] = 3,
    STATE(75), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(201), 2,
      anon_sym_COLON_EQ,
      anon_sym_COMMA,
  [1805] = 3,
    STATE(76), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(226), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1817] = 3,
    ACTIONS(230), 1,
      sym_identifier,
    STATE(77), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1828] = 3,
    ACTIONS(232), 1,
      sym_identifier,
    STATE(78), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1839] = 3,
    ACTIONS(234), 1,
      anon_sym_RBRACK,
    STATE(79), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1850] = 3,
    ACTIONS(236), 1,
      ts_builtin_sym_end,
    STATE(80), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1861] = 3,
    ACTIONS(238), 1,
      anon_sym_COLON,
    STATE(81), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1872] = 3,
    ACTIONS(240), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1883] = 3,
    ACTIONS(242), 1,
      anon_sym_COLON,
    STATE(83), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1894] = 3,
    ACTIONS(244), 1,
      anon_sym_LPAREN,
    STATE(84), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1905] = 3,
    ACTIONS(246), 1,
      sym_identifier,
    STATE(85), 1,
      sym_comment,
    ACTIONS(3), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1916] = 1,
    ACTIONS(248), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 43,
  [SMALL_STATE(4)] = 87,
  [SMALL_STATE(5)] = 131,
  [SMALL_STATE(6)] = 175,
  [SMALL_STATE(7)] = 219,
  [SMALL_STATE(8)] = 263,
  [SMALL_STATE(9)] = 290,
  [SMALL_STATE(10)] = 316,
  [SMALL_STATE(11)] = 342,
  [SMALL_STATE(12)] = 368,
  [SMALL_STATE(13)] = 394,
  [SMALL_STATE(14)] = 423,
  [SMALL_STATE(15)] = 454,
  [SMALL_STATE(16)] = 483,
  [SMALL_STATE(17)] = 514,
  [SMALL_STATE(18)] = 543,
  [SMALL_STATE(19)] = 572,
  [SMALL_STATE(20)] = 600,
  [SMALL_STATE(21)] = 628,
  [SMALL_STATE(22)] = 654,
  [SMALL_STATE(23)] = 679,
  [SMALL_STATE(24)] = 714,
  [SMALL_STATE(25)] = 739,
  [SMALL_STATE(26)] = 764,
  [SMALL_STATE(27)] = 796,
  [SMALL_STATE(28)] = 828,
  [SMALL_STATE(29)] = 860,
  [SMALL_STATE(30)] = 892,
  [SMALL_STATE(31)] = 916,
  [SMALL_STATE(32)] = 938,
  [SMALL_STATE(33)] = 960,
  [SMALL_STATE(34)] = 992,
  [SMALL_STATE(35)] = 1024,
  [SMALL_STATE(36)] = 1056,
  [SMALL_STATE(37)] = 1088,
  [SMALL_STATE(38)] = 1109,
  [SMALL_STATE(39)] = 1130,
  [SMALL_STATE(40)] = 1151,
  [SMALL_STATE(41)] = 1172,
  [SMALL_STATE(42)] = 1193,
  [SMALL_STATE(43)] = 1214,
  [SMALL_STATE(44)] = 1235,
  [SMALL_STATE(45)] = 1256,
  [SMALL_STATE(46)] = 1277,
  [SMALL_STATE(47)] = 1298,
  [SMALL_STATE(48)] = 1319,
  [SMALL_STATE(49)] = 1340,
  [SMALL_STATE(50)] = 1361,
  [SMALL_STATE(51)] = 1382,
  [SMALL_STATE(52)] = 1403,
  [SMALL_STATE(53)] = 1424,
  [SMALL_STATE(54)] = 1445,
  [SMALL_STATE(55)] = 1461,
  [SMALL_STATE(56)] = 1477,
  [SMALL_STATE(57)] = 1495,
  [SMALL_STATE(58)] = 1515,
  [SMALL_STATE(59)] = 1532,
  [SMALL_STATE(60)] = 1549,
  [SMALL_STATE(61)] = 1566,
  [SMALL_STATE(62)] = 1583,
  [SMALL_STATE(63)] = 1598,
  [SMALL_STATE(64)] = 1615,
  [SMALL_STATE(65)] = 1632,
  [SMALL_STATE(66)] = 1647,
  [SMALL_STATE(67)] = 1662,
  [SMALL_STATE(68)] = 1679,
  [SMALL_STATE(69)] = 1696,
  [SMALL_STATE(70)] = 1711,
  [SMALL_STATE(71)] = 1728,
  [SMALL_STATE(72)] = 1745,
  [SMALL_STATE(73)] = 1762,
  [SMALL_STATE(74)] = 1779,
  [SMALL_STATE(75)] = 1793,
  [SMALL_STATE(76)] = 1805,
  [SMALL_STATE(77)] = 1817,
  [SMALL_STATE(78)] = 1828,
  [SMALL_STATE(79)] = 1839,
  [SMALL_STATE(80)] = 1850,
  [SMALL_STATE(81)] = 1861,
  [SMALL_STATE(82)] = 1872,
  [SMALL_STATE(83)] = 1883,
  [SMALL_STATE(84)] = 1894,
  [SMALL_STATE(85)] = 1905,
  [SMALL_STATE(86)] = 1916,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number_literal, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number_literal, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_assignment_repeat2, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3, 0, 1),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3, 0, 1),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 6, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 6, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 5, 0, 4),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration, 5, 0, 4),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 5),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, 0, 5),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5, 0, 3),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 5, 0, 3),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 5, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 5, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_statement, 3, 0, 2),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_statement, 3, 0, 2),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 6, 0, 6),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration, 6, 0, 6),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 7, 0, 7),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 7, 0, 7),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 7, 0, 8),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration, 7, 0, 8),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 8, 0, 9),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration, 8, 0, 9),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 4, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_assignment_repeat1, 2, 0, 0),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_assignment_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [212] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_assignment_repeat2, 2, 0, 0), SHIFT_REPEAT(34),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [223] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [236] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_postulate(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "postulate",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
